import { v4 as uuidv4 } from "uuid";
import { getSupabaseClient } from "./client.js";
import { logger } from "../utils/logger.js";
import type { ProcurementCategory, TenderSource, TenderStatus } from "../types/index.js";

const SAMPLE_TENDERS = [
  {
    external_id: "TED-2026-001234",
    source: "ted_europa" as TenderSource,
    title: "Supply of MRI Scanners for Regional Hospital Network — Germany",
    description: "Framework agreement for supply, installation, and maintenance of 3T MRI systems across 12 university hospitals in Bavaria",
    buyer_name: "Bayerische Krankenhausgesellschaft",
    buyer_country: "DE",
    buyer_region: "Europe",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-05-15T08:00:00Z",
    deadline: "2026-08-30T17:00:00Z",
    original_currency: "EUR",
    original_value: 28500000,
    value_usd: 31065000,
    compliance_criteria: ["CE marking", "ISO 13485", "EU MDR 2017/745"],
    cpv_codes: ["33111000-1"],
    url: "https://ted.europa.eu/notice/2026-001234",
  },
  {
    external_id: "SAM-W912DY-26-R-0089",
    source: "sam_gov" as TenderSource,
    title: "Telehealth Platform for Veterans Affairs Medical Centers",
    description: "Acquisition of cloud-based telehealth and remote patient monitoring platform for 37 VA medical centers nationwide",
    buyer_name: "Department of Veterans Affairs",
    buyer_country: "US",
    buyer_region: "North America",
    category: "telemedicine" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-01T14:00:00Z",
    deadline: "2026-09-15T23:59:00Z",
    original_currency: "USD",
    original_value: 42000000,
    value_usd: 42000000,
    compliance_criteria: ["FedRAMP High", "HIPAA", "Section 508", "FISMA"],
    cpv_codes: ["85140000-2"],
    url: "https://sam.gov/opp/W912DY-26-R-0089",
  },
  {
    external_id: "NHS-SC-2026-PPE-0456",
    source: "nhs_supply_chain" as TenderSource,
    title: "National PPE Framework — Surgical Gowns and Drapes",
    description: "Multi-lot framework for supply of sterile and non-sterile surgical gowns, drapes, and procedural packs to NHS Trusts across England",
    buyer_name: "NHS Supply Chain",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "personal_protective_equipment" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-05-20T09:00:00Z",
    deadline: "2026-08-15T12:00:00Z",
    original_currency: "GBP",
    original_value: 15000000,
    value_usd: 19050000,
    compliance_criteria: ["BSI certification", "NHS commercial standards", "Modern Slavery Act"],
    cpv_codes: ["33199000-1"],
    url: "https://nhssupplychain.nhs.uk/frameworks/PPE-0456",
  },
  {
    external_id: "WHO-PRO-2026-DIAG-078",
    source: "who_procurement" as TenderSource,
    title: "Rapid Diagnostic Test Kits — Sub-Saharan Africa Distribution",
    description: "Procurement of WHO-prequalified rapid diagnostic test kits for malaria, HIV, and tuberculosis for distribution across 14 countries",
    buyer_name: "World Health Organization",
    buyer_country: "CH",
    buyer_region: "Africa",
    category: "diagnostics" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-03-01T10:00:00Z",
    deadline: "2026-05-15T23:59:00Z",
    original_currency: "USD",
    original_value: 8700000,
    value_usd: 8700000,
    compliance_criteria: ["WHO prequalification", "GMP certification", "ISO 13485"],
    cpv_codes: ["33124100-6"],
    url: "https://www.who.int/procurement/DIAG-078",
  },
  {
    external_id: "TED-2026-005678",
    source: "ted_europa" as TenderSource,
    title: "Laboratory Automation Systems — Swedish National Board of Health",
    description: "Design, supply, and commissioning of fully automated clinical laboratory systems for 6 regional laboratories in Sweden",
    buyer_name: "Socialstyrelsen",
    buyer_country: "SE",
    buyer_region: "Europe",
    category: "laboratory_equipment" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-10T07:00:00Z",
    deadline: "2026-09-20T16:00:00Z",
    original_currency: "SEK",
    original_value: 180000000,
    value_usd: 17280000,
    compliance_criteria: ["CE-IVD", "ISO 15189", "GDPR data handling"],
    cpv_codes: ["38000000-5"],
    url: "https://ted.europa.eu/notice/2026-005678",
  },
  {
    external_id: "SAM-HHS-26-R-0312",
    source: "sam_gov" as TenderSource,
    title: "Electronic Health Records Modernisation — Indian Health Service",
    description: "Implementation of next-generation EHR system across 46 Indian Health Service hospitals and 340 outpatient clinics",
    buyer_name: "Indian Health Service",
    buyer_country: "US",
    buyer_region: "North America",
    category: "health_it" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-15T14:00:00Z",
    deadline: "2026-10-01T23:59:00Z",
    original_currency: "USD",
    original_value: 67000000,
    value_usd: 67000000,
    compliance_criteria: ["HIPAA", "Section 508", "HL7 FHIR R4", "FedRAMP Moderate"],
    cpv_codes: ["48000000-8"],
    url: "https://sam.gov/opp/HHS-26-R-0312",
  },
  {
    external_id: "TED-2026-008901",
    source: "ted_europa" as TenderSource,
    title: "Cardiac Catheterisation Laboratory Equipment — Paris Hospitals",
    description: "Supply and installation of 8 cardiac catheterisation laboratory systems for Assistance Publique – Hôpitaux de Paris",
    buyer_name: "AP-HP (Assistance Publique – Hôpitaux de Paris)",
    buyer_country: "FR",
    buyer_region: "Europe",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-04-20T09:00:00Z",
    deadline: "2026-07-31T17:00:00Z",
    original_currency: "EUR",
    original_value: 22000000,
    value_usd: 23980000,
    compliance_criteria: ["CE marking", "ISO 13485", "EU MDR 2017/745", "ANSM registration"],
    cpv_codes: ["33100000-1"],
    url: "https://ted.europa.eu/notice/2026-008901",
  },
  {
    external_id: "NHS-SC-2026-SURG-0789",
    source: "nhs_supply_chain" as TenderSource,
    title: "Orthopaedic Implants and Instruments Framework",
    description: "National framework for hip, knee, shoulder, and trauma implant systems including surgical instruments and associated services",
    buyer_name: "NHS Supply Chain",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-01T08:00:00Z",
    deadline: "2026-09-01T12:00:00Z",
    original_currency: "GBP",
    original_value: 85000000,
    value_usd: 107950000,
    compliance_criteria: ["BSI certification", "MHRA registration", "NHS commercial standards"],
    cpv_codes: ["33183000-6"],
    url: "https://nhssupplychain.nhs.uk/frameworks/SURG-0789",
  },
  {
    external_id: "WHO-PRO-2026-VAX-092",
    source: "who_procurement" as TenderSource,
    title: "Cold Chain Equipment for Vaccine Distribution — Southeast Asia",
    description: "Solar-powered vaccine refrigerators and cold chain monitoring systems for immunisation programmes across 6 ASEAN countries",
    buyer_name: "World Health Organization",
    buyer_country: "CH",
    buyer_region: "Asia-Pacific",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-05-01T10:00:00Z",
    deadline: "2026-08-01T23:59:00Z",
    original_currency: "USD",
    original_value: 14500000,
    value_usd: 14500000,
    compliance_criteria: ["WHO PQS prequalification", "IEC 60068", "GMP certification"],
    cpv_codes: ["33100000-1"],
    url: "https://www.who.int/procurement/VAX-092",
  },
  {
    external_id: "SAM-DOD-26-R-0455",
    source: "sam_gov" as TenderSource,
    title: "Automated Pharmacy Dispensing Systems — Military Health System",
    description: "Supply and installation of automated medication dispensing cabinets for 55 military treatment facilities worldwide",
    buyer_name: "Defense Health Agency",
    buyer_country: "US",
    buyer_region: "North America",
    category: "pharmaceuticals" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-02-01T14:00:00Z",
    deadline: "2026-04-30T23:59:00Z",
    original_currency: "USD",
    original_value: 38000000,
    value_usd: 38000000,
    compliance_criteria: ["FDA 21 CFR Part 11", "HIPAA", "DoD cybersecurity"],
    cpv_codes: ["33600000-6"],
    url: "https://sam.gov/opp/DOD-26-R-0455",
  },
  {
    external_id: "TED-2026-011234",
    source: "ted_europa" as TenderSource,
    title: "Point-of-Care Ultrasound Devices — Netherlands Hospital Group",
    description: "Framework agreement for portable and handheld ultrasound systems across 8 hospitals in the Erasmus MC network",
    buyer_name: "Erasmus MC",
    buyer_country: "NL",
    buyer_region: "Europe",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-20T07:00:00Z",
    deadline: "2026-09-30T17:00:00Z",
    original_currency: "EUR",
    original_value: 5200000,
    value_usd: 5668000,
    compliance_criteria: ["CE marking", "ISO 13485", "EU MDR 2017/745"],
    cpv_codes: ["33112000-8"],
    url: "https://ted.europa.eu/notice/2026-011234",
  },
  {
    external_id: "NHS-SC-2026-DIAG-1023",
    source: "nhs_supply_chain" as TenderSource,
    title: "Next-Generation Sequencing Platforms — NHS Genomic Medicine",
    description: "Supply of NGS sequencing instruments and reagent kits for the NHS Genomic Medicine Service across 7 Genomic Laboratory Hubs",
    buyer_name: "NHS England",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "diagnostics" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-05T08:00:00Z",
    deadline: "2026-08-20T12:00:00Z",
    original_currency: "GBP",
    original_value: 32000000,
    value_usd: 40640000,
    compliance_criteria: ["UKAS accreditation", "CE-IVD", "ISO 15189"],
    cpv_codes: ["33120000-7"],
    url: "https://nhssupplychain.nhs.uk/frameworks/DIAG-1023",
  },
  {
    external_id: "SAM-CDC-26-R-0678",
    source: "sam_gov" as TenderSource,
    title: "Biosafety Level 3 Laboratory Upgrades — CDC Facilities",
    description: "Design and construction of BSL-3 containment upgrades at 4 CDC laboratory facilities including HVAC and decontamination systems",
    buyer_name: "Centers for Disease Control and Prevention",
    buyer_country: "US",
    buyer_region: "North America",
    category: "hospital_infrastructure" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-05-10T14:00:00Z",
    deadline: "2026-08-10T23:59:00Z",
    original_currency: "USD",
    original_value: 29000000,
    value_usd: 29000000,
    compliance_criteria: ["BMBL 6th edition", "OSHA 29 CFR 1910", "EPA regulations"],
    cpv_codes: ["45000000-7"],
    url: "https://sam.gov/opp/CDC-26-R-0678",
  },
  {
    external_id: "WHO-PRO-2026-PPE-103",
    source: "who_procurement" as TenderSource,
    title: "Surgical Masks and N95 Respirators — Global Emergency Stockpile",
    description: "Replenishment of WHO emergency stockpile with surgical masks, N95 respirators, and face shields for pandemic preparedness",
    buyer_name: "World Health Organization",
    buyer_country: "CH",
    buyer_region: "Africa",
    category: "personal_protective_equipment" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-01-15T10:00:00Z",
    deadline: "2026-03-30T23:59:00Z",
    original_currency: "USD",
    original_value: 21000000,
    value_usd: 21000000,
    compliance_criteria: ["WHO prequalification", "NIOSH N95 approval", "EN 14683"],
    cpv_codes: ["33199000-1"],
    url: "https://www.who.int/procurement/PPE-103",
  },
  {
    external_id: "TED-2026-014567",
    source: "ted_europa" as TenderSource,
    title: "Hospital Information System — Italian National Health Service",
    description: "Cloud-based HIS platform for 15 public hospitals in Lombardy including patient management, scheduling, and clinical documentation",
    buyer_name: "Regione Lombardia — Direzione Generale Welfare",
    buyer_country: "IT",
    buyer_region: "Europe",
    category: "health_it" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-18T09:00:00Z",
    deadline: "2026-10-15T17:00:00Z",
    original_currency: "EUR",
    original_value: 45000000,
    value_usd: 49050000,
    compliance_criteria: ["GDPR", "AgID cloud qualification", "HL7 FHIR", "ISO 27001"],
    cpv_codes: ["48000000-8"],
    url: "https://ted.europa.eu/notice/2026-014567",
  },
  // Global Surgical Instruments Expansion
  {
    external_id: "TED-2026-SURG-001",
    source: "ted_europa" as TenderSource,
    title: "Minimally Invasive Surgery Instruments — Spanish Healthcare System",
    description: "Supply of laparoscopic instruments, trocars, and insufflation equipment for 28 Spanish public hospitals",
    buyer_name: "Ministerio de Sanidad — Spain",
    buyer_country: "ES",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-07-01T08:00:00Z",
    deadline: "2026-10-15T17:00:00Z",
    original_currency: "EUR",
    original_value: 12500000,
    value_usd: 13625000,
    compliance_criteria: ["CE marking", "ISO 13485", "EU MDR 2017/745"],
    cpv_codes: ["33183000-6"],
    url: "https://ted.europa.eu/notice/2026-SURG-001",
  },
  {
    external_id: "SAM-DOD-26-SURG-0234",
    source: "sam_gov" as TenderSource,
    title: "Combat Casualty Care Surgical Instrument Sets — U.S. Military",
    description: "Supply of combat trauma surgical kits and instruments for field hospitals, forward operating bases, and military medical ships",
    buyer_name: "U.S. Army Medical Command",
    buyer_country: "US",
    buyer_region: "North America",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-25T14:00:00Z",
    deadline: "2026-10-01T23:59:00Z",
    original_currency: "USD",
    original_value: 28500000,
    value_usd: 28500000,
    compliance_criteria: ["FDA approval", "NATO standardization", "Military durability specs"],
    cpv_codes: ["33183000-6"],
    url: "https://sam.gov/opp/DOD-26-SURG-0234",
  },
  {
    external_id: "NHS-SC-2026-SURG-1234",
    source: "nhs_supply_chain" as TenderSource,
    title: "Vascular and Endovascular Surgical Instruments — NHS England",
    description: "Framework for vascular clamps, retractors, and specialized instruments for vascular surgery across 45 NHS Trusts",
    buyer_name: "NHS England",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-07-05T08:00:00Z",
    deadline: "2026-09-30T12:00:00Z",
    original_currency: "GBP",
    original_value: 18000000,
    value_usd: 22860000,
    compliance_criteria: ["MHRA registration", "BSI certification", "NHS commercial standards"],
    cpv_codes: ["33183000-6"],
    url: "https://nhssupplychain.nhs.uk/frameworks/SURG-1234",
  },
  {
    external_id: "TED-2026-SURG-002",
    source: "ted_europa" as TenderSource,
    title: "Cardiothoracic Surgery Instruments — German University Hospitals",
    description: "Supply of specialized cardiac and thoracic surgical instruments including retractors, spreaders, and specialized forceps for 12 German medical centers",
    buyer_name: "Deutscher Ärzte-Verlag",
    buyer_country: "DE",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-28T07:00:00Z",
    deadline: "2026-10-10T17:00:00Z",
    original_currency: "EUR",
    original_value: 9800000,
    value_usd: 10682000,
    compliance_criteria: ["CE marking", "ISO 13485", "DIN EN standards"],
    cpv_codes: ["33183000-6"],
    url: "https://ted.europa.eu/notice/2026-SURG-002",
  },
  {
    external_id: "WHO-PRO-2026-SURG-104",
    source: "who_procurement" as TenderSource,
    title: "Essential Surgical Instruments — Africa Health Initiative",
    description: "Comprehensive surgical instrument kits for obstetrics, trauma, and general surgery for 42 health facilities across 8 African countries",
    buyer_name: "World Health Organization",
    buyer_country: "CH",
    buyer_region: "Africa",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-20T10:00:00Z",
    deadline: "2026-09-20T23:59:00Z",
    original_currency: "USD",
    original_value: 7200000,
    value_usd: 7200000,
    compliance_criteria: ["WHO prequalification", "ISO 13485", "GMP certification"],
    cpv_codes: ["33183000-6"],
    url: "https://www.who.int/procurement/SURG-104",
  },
  {
    external_id: "SAM-HHS-26-SURG-0456",
    source: "sam_gov" as TenderSource,
    title: "Obstetric and Gynecological Surgery Instruments — Indian Health Service",
    description: "Supply of OB/GYN surgical instruments including specula, forceps, and specialized delivery kits for 36 IHS healthcare facilities",
    buyer_name: "Indian Health Service",
    buyer_country: "US",
    buyer_region: "North America",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-30T14:00:00Z",
    deadline: "2026-09-30T23:59:00Z",
    original_currency: "USD",
    original_value: 5600000,
    value_usd: 5600000,
    compliance_criteria: ["FDA approval", "HIPAA", "Section 508"],
    cpv_codes: ["33183000-6"],
    url: "https://sam.gov/opp/HHS-26-SURG-0456",
  },
  {
    external_id: "TED-2026-SURG-003",
    source: "ted_europa" as TenderSource,
    title: "Neurosurgery and Spinal Surgery Instruments — French Neurology Centers",
    description: "Supply of specialized neurosurgical instruments, drills, and spinal fixation systems for 15 French neurology and spine centers",
    buyer_name: "Assistance Publique – Hôpitaux de Paris",
    buyer_country: "FR",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-07-02T09:00:00Z",
    deadline: "2026-10-20T17:00:00Z",
    original_currency: "EUR",
    original_value: 16400000,
    value_usd: 17876000,
    compliance_criteria: ["CE marking", "ISO 13485", "ANSM registration"],
    cpv_codes: ["33183000-6"],
    url: "https://ted.europa.eu/notice/2026-SURG-003",
  },
  {
    external_id: "CANADA-2026-SURG-0567",
    source: "canada_buys" as TenderSource,
    title: "Orthopedic Surgery Instrument Sets — Canadian Public Health",
    description: "Supply of orthopedic surgical instruments including bone saws, plates, screws, and retractors for 22 Canadian provincial hospitals",
    buyer_name: "Canadian Public Health Authority",
    buyer_country: "CA",
    buyer_region: "North America",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-07-03T12:00:00Z",
    deadline: "2026-10-05T20:00:00Z",
    original_currency: "CAD",
    original_value: 11200000,
    value_usd: 8316800,
    compliance_criteria: ["Health Canada approval", "ISO 13485", "CSA standards"],
    cpv_codes: ["33183000-6"],
    url: "https://canadabuys.canada.ca/opportunity/2026-SURG-0567",
  },
  {
    external_id: "NHS-SC-2026-SURG-2345",
    source: "nhs_supply_chain" as TenderSource,
    title: "General Surgery Instrument Maintenance and Repair — NHS Scotland",
    description: "Maintenance, repair, and refurbishment services for surgical instruments across 18 NHS Scotland hospitals",
    buyer_name: "NHS Scotland",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-07-04T08:00:00Z",
    deadline: "2026-09-15T12:00:00Z",
    original_currency: "GBP",
    original_value: 4200000,
    value_usd: 5334000,
    compliance_criteria: ["MHRA compliance", "ISO 13485 maintenance", "NHS standards"],
    cpv_codes: ["33183000-6"],
    url: "https://nhssupplychain.nhs.uk/frameworks/SURG-2345",
  },
  {
    external_id: "TED-2026-SURG-004",
    source: "ted_europa" as TenderSource,
    title: "ENT (Otorhinolaryngology) Surgery Instruments — Dutch Healthcare",
    description: "Supply of otolaryngological surgical instruments including endoscopes, specula, and microsurgical instruments for 16 Dutch hospitals",
    buyer_name: "GGZ Nederland",
    buyer_country: "NL",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-07-06T08:00:00Z",
    deadline: "2026-10-25T17:00:00Z",
    original_currency: "EUR",
    original_value: 7900000,
    value_usd: 8609000,
    compliance_criteria: ["CE marking", "ISO 13485", "EU MDR 2017/745"],
    cpv_codes: ["33183000-6"],
    url: "https://ted.europa.eu/notice/2026-SURG-004",
  },
  {
    external_id: "SAM-VA-26-SURG-0678",
    source: "sam_gov" as TenderSource,
    title: "Ophthalmic Surgery Instruments — Veterans Affairs Medical Centers",
    description: "Supply of ophthalmic surgical instruments including microsurgical forceps, scissors, and cannulas for 38 VA hospitals",
    buyer_name: "Department of Veterans Affairs",
    buyer_country: "US",
    buyer_region: "North America",
    category: "surgical_instruments" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-05-15T14:00:00Z",
    deadline: "2026-07-30T23:59:00Z",
    original_currency: "USD",
    original_value: 4800000,
    value_usd: 4800000,
    compliance_criteria: ["FDA approval", "HIPAA", "VA medical standards"],
    cpv_codes: ["33183000-6"],
    url: "https://sam.gov/opp/VA-26-SURG-0678",
  },
  {
    external_id: "TED-2026-SURG-005",
    source: "ted_europa" as TenderSource,
    title: "Pediatric Surgery Instruments — Scandinavian Children's Hospitals",
    description: "Specialized pediatric surgical instruments for trauma, general surgery, and interventional procedures across 9 Nordic children's hospitals",
    buyer_name: "Nordic Healthcare Procurement Consortium",
    buyer_country: "SE",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-07-08T07:00:00Z",
    deadline: "2026-10-30T17:00:00Z",
    original_currency: "SEK",
    original_value: 6800000,
    value_usd: 651500,
    compliance_criteria: ["CE marking", "ISO 13485", "Nordic healthcare standards"],
    cpv_codes: ["33183000-6"],
    url: "https://ted.europa.eu/notice/2026-SURG-005",
  },
  // ===== Medical Devices — Asia-Pacific & Africa =====
  {
    external_id: "MANUAL-JP-2026-MED-001",
    source: "manual" as TenderSource,
    title: "Surgical Robotic Systems — Tokyo Metropolitan Hospital Network",
    description: "Procurement of robotic-assisted surgery platforms for urology, gynecology, and general surgery across 9 Tokyo metropolitan hospitals",
    buyer_name: "Tokyo Metropolitan Government Bureau of Health",
    buyer_country: "JP",
    buyer_region: "Asia-Pacific",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-22T02:00:00Z",
    deadline: "2026-09-25T15:00:00Z",
    original_currency: "JPY",
    original_value: 2100000000,
    value_usd: 14070000,
    compliance_criteria: ["PMDA approval", "ISO 13485", "JIS medical device standards"],
    cpv_codes: ["33169000-2"],
    url: "https://www.metro.tokyo.lg.jp/procurement/2026-MED-001",
  },
  {
    external_id: "MANUAL-AU-2026-MED-002",
    source: "manual" as TenderSource,
    title: "Diagnostic Imaging Equipment — Rural Health Services Australia",
    description: "Supply of digital radiography and CT systems for 24 rural and remote hospitals across Queensland and Western Australia",
    buyer_name: "Australian Government Department of Health",
    buyer_country: "AU",
    buyer_region: "Asia-Pacific",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-18T23:00:00Z",
    deadline: "2026-09-10T09:00:00Z",
    original_currency: "AUD",
    original_value: 18500000,
    value_usd: 12136500,
    compliance_criteria: ["TGA approval", "ISO 13485", "ARPANSA radiation safety"],
    cpv_codes: ["33111000-1"],
    url: "https://www.tenders.gov.au/atm/2026-MED-002",
  },
  {
    external_id: "MANUAL-ZA-2026-MED-003",
    source: "manual" as TenderSource,
    title: "Portable Ventilators and Patient Monitors — South Africa Provincial Hospitals",
    description: "Supply of portable ventilators, multi-parameter patient monitors, and infusion pumps for 31 provincial hospitals in KwaZulu-Natal and Gauteng",
    buyer_name: "National Department of Health — South Africa",
    buyer_country: "ZA",
    buyer_region: "Africa",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-15T08:00:00Z",
    deadline: "2026-09-01T16:00:00Z",
    original_currency: "USD",
    original_value: 9400000,
    value_usd: 9400000,
    compliance_criteria: ["SAHPRA registration", "ISO 13485", "SANS medical device standards"],
    cpv_codes: ["33157000-5"],
    url: "https://www.etenders.gov.za/2026-MED-003",
  },
  // ===== Pharmaceuticals — Asia-Pacific & Africa =====
  {
    external_id: "WORLD-BANK-IN-2026-PHARM-201",
    source: "world_bank" as TenderSource,
    title: "Essential Generic Medicines — India National Health Mission",
    description: "Procurement and distribution of WHO-listed essential generic medicines for primary health centers across 6 Indian states",
    buyer_name: "National Health Mission — Ministry of Health and Family Welfare",
    buyer_country: "IN",
    buyer_region: "Asia-Pacific",
    category: "pharmaceuticals" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-10T05:00:00Z",
    deadline: "2026-08-25T18:00:00Z",
    original_currency: "USD",
    original_value: 22300000,
    value_usd: 22300000,
    compliance_criteria: ["WHO GMP certification", "CDSCO approval", "WHO prequalification"],
    cpv_codes: ["33690000-3"],
    url: "https://projects.worldbank.org/en/procurement/2026-PHARM-201",
  },
  {
    external_id: "WORLD-BANK-NG-2026-PHARM-202",
    source: "world_bank" as TenderSource,
    title: "Antimalarial and Antibiotic Drug Supply — Nigeria Federal Ministry of Health",
    description: "Procurement of artemisinin-based combination therapies and broad-spectrum antibiotics for national malaria and infection control programs",
    buyer_name: "Federal Ministry of Health — Nigeria",
    buyer_country: "NG",
    buyer_region: "Africa",
    category: "pharmaceuticals" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-05T09:00:00Z",
    deadline: "2026-08-20T17:00:00Z",
    original_currency: "USD",
    original_value: 15800000,
    value_usd: 15800000,
    compliance_criteria: ["WHO prequalification", "NAFDAC registration", "GMP certification"],
    cpv_codes: ["33651600-4"],
    url: "https://projects.worldbank.org/en/procurement/2026-PHARM-202",
  },
  {
    external_id: "MANUAL-AU-2026-PHARM-203",
    source: "manual" as TenderSource,
    title: "Oncology Medicines Supply — Australian Public Cancer Centers",
    description: "Supply of chemotherapy and targeted oncology medicines for the Pharmaceutical Benefits Scheme across 40 public cancer treatment centers",
    buyer_name: "Australian Government Department of Health",
    buyer_country: "AU",
    buyer_region: "Asia-Pacific",
    category: "pharmaceuticals" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-03-12T23:00:00Z",
    deadline: "2026-05-20T09:00:00Z",
    original_currency: "AUD",
    original_value: 34200000,
    value_usd: 22439400,
    compliance_criteria: ["TGA approval", "PBS listing", "GMP certification"],
    cpv_codes: ["33652100-6"],
    url: "https://www.tenders.gov.au/atm/2026-PHARM-203",
  },
  // ===== Health IT — Asia-Pacific & Africa =====
  {
    external_id: "MANUAL-SG-2026-HIT-301",
    source: "manual" as TenderSource,
    title: "National Electronic Health Record Integration — Singapore",
    description: "Integration of hospital, polyclinic, and pharmacy systems into the National Electronic Health Record platform across all public healthcare clusters",
    buyer_name: "Ministry of Health — Singapore (Synapxe)",
    buyer_country: "SG",
    buyer_region: "Asia-Pacific",
    category: "health_it" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-12T01:00:00Z",
    deadline: "2026-09-05T10:00:00Z",
    original_currency: "SGD",
    original_value: 28000000,
    value_usd: 20720000,
    compliance_criteria: ["HL7 FHIR", "PDPA compliance", "ISO 27001", "Government cloud accreditation"],
    cpv_codes: ["48000000-8"],
    url: "https://www.gebiz.gov.sg/2026-HIT-301",
  },
  {
    external_id: "WORLD-BANK-KE-2026-HIT-302",
    source: "world_bank" as TenderSource,
    title: "Mobile Health Data Platform — Kenya Rural Clinics",
    description: "Deployment of a mobile-first health information system for maternal health tracking and disease surveillance across 400 rural clinics",
    buyer_name: "Ministry of Health — Kenya",
    buyer_country: "KE",
    buyer_region: "Africa",
    category: "health_it" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-08T08:00:00Z",
    deadline: "2026-08-30T17:00:00Z",
    original_currency: "USD",
    original_value: 4600000,
    value_usd: 4600000,
    compliance_criteria: ["ODK/DHIS2 compatibility", "Data protection act compliance", "WHO health data standards"],
    cpv_codes: ["48000000-8"],
    url: "https://projects.worldbank.org/en/procurement/2026-HIT-302",
  },
  {
    external_id: "MANUAL-KR-2026-HIT-303",
    source: "manual" as TenderSource,
    title: "AI Diagnostic Support System — South Korea Public Hospitals",
    description: "Deployment of AI-assisted radiology and pathology diagnostic support software across 18 national public hospitals",
    buyer_name: "National Health Insurance Service — South Korea",
    buyer_country: "KR",
    buyer_region: "Asia-Pacific",
    category: "health_it" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-25T00:00:00Z",
    deadline: "2026-09-15T09:00:00Z",
    original_currency: "USD",
    original_value: 11200000,
    value_usd: 11200000,
    compliance_criteria: ["MFDS AI/software approval", "ISO 27001", "HL7 FHIR"],
    cpv_codes: ["48000000-8"],
    url: "https://www.g2b.go.kr/2026-HIT-303",
  },
  // ===== Laboratory Equipment — Africa & Asia-Pacific =====
  {
    external_id: "WORLD-BANK-EG-2026-LAB-401",
    source: "world_bank" as TenderSource,
    title: "Clinical Chemistry Analyzers — Egypt Ministry of Health Labs",
    description: "Supply of automated clinical chemistry and hematology analyzers for 45 central and regional public health laboratories",
    buyer_name: "Ministry of Health and Population — Egypt",
    buyer_country: "EG",
    buyer_region: "Africa",
    category: "laboratory_equipment" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-14T09:00:00Z",
    deadline: "2026-09-01T15:00:00Z",
    original_currency: "USD",
    original_value: 6300000,
    value_usd: 6300000,
    compliance_criteria: ["EDA registration", "ISO 15189", "CE-IVD"],
    cpv_codes: ["38000000-5"],
    url: "https://projects.worldbank.org/en/procurement/2026-LAB-401",
  },
  {
    external_id: "MANUAL-AU-2026-LAB-402",
    source: "manual" as TenderSource,
    title: "Genomics Sequencing Lab Equipment — Australian Genomics Health Alliance",
    description: "Supply of next-generation sequencing platforms and bioinformatics infrastructure for 7 genomics reference laboratories",
    buyer_name: "Australian Genomics Health Alliance",
    buyer_country: "AU",
    buyer_region: "Asia-Pacific",
    category: "laboratory_equipment" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-20T23:00:00Z",
    deadline: "2026-09-18T09:00:00Z",
    original_currency: "AUD",
    original_value: 13800000,
    value_usd: 9054600,
    compliance_criteria: ["TGA approval", "ISO 15189", "NATA accreditation"],
    cpv_codes: ["38000000-5"],
    url: "https://www.tenders.gov.au/atm/2026-LAB-402",
  },
  // ===== Hospital Infrastructure — Asia-Pacific & Africa =====
  {
    external_id: "WORLD-BANK-IN-2026-INFRA-501",
    source: "world_bank" as TenderSource,
    title: "Modular ICU Construction — India State Hospital Upgrade Program",
    description: "Design and construction of modular prefabricated ICU wards with HVAC and medical gas systems for 12 state government hospitals",
    buyer_name: "National Health Mission — Ministry of Health and Family Welfare",
    buyer_country: "IN",
    buyer_region: "Asia-Pacific",
    category: "hospital_infrastructure" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-01T05:00:00Z",
    deadline: "2026-08-15T18:00:00Z",
    original_currency: "USD",
    original_value: 31500000,
    value_usd: 31500000,
    compliance_criteria: ["NABH accreditation standards", "NBC building code", "Biomedical waste rules"],
    cpv_codes: ["45215140-0"],
    url: "https://projects.worldbank.org/en/procurement/2026-INFRA-501",
  },
  {
    external_id: "WORLD-BANK-KE-2026-INFRA-502",
    source: "world_bank" as TenderSource,
    title: "Solar-Powered Hospital Electrification — Kenya Rural Facilities",
    description: "Installation of solar power systems and backup generators for 85 rural health facilities lacking reliable grid electricity",
    buyer_name: "Ministry of Health — Kenya",
    buyer_country: "KE",
    buyer_region: "Africa",
    category: "hospital_infrastructure" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-11T08:00:00Z",
    deadline: "2026-08-28T17:00:00Z",
    original_currency: "USD",
    original_value: 8900000,
    value_usd: 8900000,
    compliance_criteria: ["IEC solar standards", "Kenya Bureau of Standards", "WHO facility electrification guidelines"],
    cpv_codes: ["45259000-7"],
    url: "https://projects.worldbank.org/en/procurement/2026-INFRA-502",
  },
  // ===== PPE — Asia-Pacific & Africa =====
  {
    external_id: "WORLD-BANK-IN-2026-PPE-601",
    source: "world_bank" as TenderSource,
    title: "Surgical Gloves and Gowns National Stockpile — India",
    description: "Procurement of sterile surgical gloves, isolation gowns, and protective eyewear for national pandemic preparedness stockpile",
    buyer_name: "National Health Mission — Ministry of Health and Family Welfare",
    buyer_country: "IN",
    buyer_region: "Asia-Pacific",
    category: "personal_protective_equipment" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-06T05:00:00Z",
    deadline: "2026-08-18T18:00:00Z",
    original_currency: "USD",
    original_value: 5100000,
    value_usd: 5100000,
    compliance_criteria: ["CDSCO approval", "ISO 13485", "ASTM F1671"],
    cpv_codes: ["33199000-1"],
    url: "https://projects.worldbank.org/en/procurement/2026-PPE-601",
  },
  {
    external_id: "MANUAL-ZA-2026-PPE-602",
    source: "manual" as TenderSource,
    title: "N95 Respirators and Face Shields — South Africa Public Health Department",
    description: "Supply of NIOSH/SANS-certified N95 respirators and reusable face shields for frontline healthcare workers nationwide",
    buyer_name: "National Department of Health — South Africa",
    buyer_country: "ZA",
    buyer_region: "Africa",
    category: "personal_protective_equipment" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-02-20T08:00:00Z",
    deadline: "2026-04-25T16:00:00Z",
    original_currency: "USD",
    original_value: 3700000,
    value_usd: 3700000,
    compliance_criteria: ["SAHPRA registration", "SANS 50149", "NIOSH N95 approval"],
    cpv_codes: ["33199000-1"],
    url: "https://www.etenders.gov.za/2026-PPE-602",
  },
  // ===== Diagnostics — Asia-Pacific & Africa =====
  {
    external_id: "MANUAL-AU-2026-DIAG-701",
    source: "manual" as TenderSource,
    title: "Respiratory Diagnostic Testing Kits — Australian Public Health Laboratories",
    description: "Supply of PCR and rapid antigen testing kits for influenza, COVID-19, and RSV surveillance across state public health laboratories",
    buyer_name: "Australian Government Department of Health",
    buyer_country: "AU",
    buyer_region: "Asia-Pacific",
    category: "diagnostics" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-16T23:00:00Z",
    deadline: "2026-09-05T09:00:00Z",
    original_currency: "AUD",
    original_value: 7600000,
    value_usd: 4989200,
    compliance_criteria: ["TGA approval", "ISO 13485", "CE-IVD"],
    cpv_codes: ["33124100-6"],
    url: "https://www.tenders.gov.au/atm/2026-DIAG-701",
  },
  {
    external_id: "WORLD-BANK-NG-2026-DIAG-702",
    source: "world_bank" as TenderSource,
    title: "HIV and TB Rapid Test Kits — Nigeria National Disease Control",
    description: "Procurement of WHO-prequalified HIV and tuberculosis rapid diagnostic kits for distribution across 36 states and the FCT",
    buyer_name: "Federal Ministry of Health — Nigeria",
    buyer_country: "NG",
    buyer_region: "Africa",
    category: "diagnostics" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-09T09:00:00Z",
    deadline: "2026-08-22T17:00:00Z",
    original_currency: "USD",
    original_value: 9900000,
    value_usd: 9900000,
    compliance_criteria: ["WHO prequalification", "NAFDAC registration", "GMP certification"],
    cpv_codes: ["33124100-6"],
    url: "https://projects.worldbank.org/en/procurement/2026-DIAG-702",
  },
  // ===== Telemedicine — Asia-Pacific & Africa =====
  {
    external_id: "WORLD-BANK-IN-2026-TELE-801",
    source: "world_bank" as TenderSource,
    title: "Telemedicine Platform — India Rural Health Mission",
    description: "Deployment of a teleconsultation platform connecting primary health centers in remote districts with specialist doctors in urban hospitals",
    buyer_name: "National Health Mission — Ministry of Health and Family Welfare",
    buyer_country: "IN",
    buyer_region: "Asia-Pacific",
    category: "telemedicine" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-03T05:00:00Z",
    deadline: "2026-08-19T18:00:00Z",
    original_currency: "USD",
    original_value: 6700000,
    value_usd: 6700000,
    compliance_criteria: ["CDSCO telemedicine guidelines", "Data protection compliance", "HL7 FHIR"],
    cpv_codes: ["85140000-2"],
    url: "https://projects.worldbank.org/en/procurement/2026-TELE-801",
  },
  {
    external_id: "MANUAL-AU-2026-TELE-802",
    source: "manual" as TenderSource,
    title: "Remote Patient Monitoring — Australian Aged Care Providers",
    description: "Supply of remote vital-sign monitoring devices and telehealth software for residential and in-home aged care programs",
    buyer_name: "Australian Government Department of Health",
    buyer_country: "AU",
    buyer_region: "Asia-Pacific",
    category: "telemedicine" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-27T23:00:00Z",
    deadline: "2026-09-20T09:00:00Z",
    original_currency: "AUD",
    original_value: 5400000,
    value_usd: 3542400,
    compliance_criteria: ["TGA approval", "Aged Care Quality Standards", "Privacy Act compliance"],
    cpv_codes: ["85140000-2"],
    url: "https://www.tenders.gov.au/atm/2026-TELE-802",
  },
  {
    external_id: "WORLD-BANK-KE-2026-TELE-803",
    source: "world_bank" as TenderSource,
    title: "mHealth Telehealth Consultation Platform — Kenya",
    description: "Development of an SMS and app-based telehealth consultation service linking community health workers with regional hospitals",
    buyer_name: "Ministry of Health — Kenya",
    buyer_country: "KE",
    buyer_region: "Africa",
    category: "telemedicine" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-13T08:00:00Z",
    deadline: "2026-08-29T17:00:00Z",
    original_currency: "USD",
    original_value: 3200000,
    value_usd: 3200000,
    compliance_criteria: ["Data protection act compliance", "WHO digital health guidelines", "ODK/DHIS2 compatibility"],
    cpv_codes: ["85140000-2"],
    url: "https://projects.worldbank.org/en/procurement/2026-TELE-803",
  },
  // ===== Clinical Services — Europe, North America & Asia-Pacific =====
  {
    external_id: "NHS-SC-2026-CLIN-901",
    source: "nhs_supply_chain" as TenderSource,
    title: "Outsourced Radiology Reporting Services — NHS England",
    description: "Framework for outsourced teleradiology reporting to reduce imaging backlogs across 30 NHS Trusts",
    buyer_name: "NHS England",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "clinical_services" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-19T08:00:00Z",
    deadline: "2026-09-10T12:00:00Z",
    original_currency: "GBP",
    original_value: 22000000,
    value_usd: 27940000,
    compliance_criteria: ["CQC registration", "GMC/RCR reporting standards", "NHS commercial standards"],
    cpv_codes: ["85121200-5"],
    url: "https://nhssupplychain.nhs.uk/frameworks/CLIN-901",
  },
  {
    external_id: "SAM-VA-26-CLIN-0902",
    source: "sam_gov" as TenderSource,
    title: "Contracted Nursing Staffing Services — Veterans Affairs Medical Centers",
    description: "Supplemental contracted nursing staff services for critical care, emergency, and med-surg units at 25 VA medical centers",
    buyer_name: "Department of Veterans Affairs",
    buyer_country: "US",
    buyer_region: "North America",
    category: "clinical_services" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-21T14:00:00Z",
    deadline: "2026-09-12T23:59:00Z",
    original_currency: "USD",
    original_value: 41000000,
    value_usd: 41000000,
    compliance_criteria: ["Joint Commission standards", "HIPAA", "VA credentialing requirements"],
    cpv_codes: ["85141200-1"],
    url: "https://sam.gov/opp/VA-26-CLIN-0902",
  },
  {
    external_id: "MANUAL-AU-2026-CLIN-903",
    source: "manual" as TenderSource,
    title: "Pathology Outsourcing Services — Australian Public Hospital Network",
    description: "Outsourced anatomical pathology and histopathology reporting services for regional public hospitals lacking on-site specialists",
    buyer_name: "Australian Government Department of Health",
    buyer_country: "AU",
    buyer_region: "Asia-Pacific",
    category: "clinical_services" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-24T23:00:00Z",
    deadline: "2026-09-14T09:00:00Z",
    original_currency: "AUD",
    original_value: 9200000,
    value_usd: 6037200,
    compliance_criteria: ["NATA accreditation", "RCPA standards", "TGA approval"],
    cpv_codes: ["85145000-7"],
    url: "https://www.tenders.gov.au/atm/2026-CLIN-903",
  },
  // ===== Social Care — Europe & North America =====
  {
    external_id: "CONTRACTS-FINDER-2026-SOC-1001",
    source: "contracts_finder" as TenderSource,
    title: "Adult Social Care Digital Case Management System — UK Local Authorities",
    description: "Supply and implementation of a digital case management platform for adult social care assessments across 14 English local authorities",
    buyer_name: "Local Government Association — England",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "social_care" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-17T08:00:00Z",
    deadline: "2026-09-08T12:00:00Z",
    original_currency: "GBP",
    original_value: 6800000,
    value_usd: 8636000,
    compliance_criteria: ["Care Act 2014 compliance", "GDPR", "DSPT (Data Security and Protection Toolkit)"],
    cpv_codes: ["85312000-9"],
    url: "https://www.contractsfinder.service.gov.uk/notice/2026-SOC-1001",
  },
  {
    external_id: "TED-2026-SOC-1002",
    source: "ted_europa" as TenderSource,
    title: "Elderly Care Home Support Services — German Federal States Framework",
    description: "Framework for outsourced nursing and personal care support services in publicly funded elderly care homes across Bavaria and Baden-Württemberg",
    buyer_name: "Deutscher Ärzte-Verlag",
    buyer_country: "DE",
    buyer_region: "Europe",
    category: "social_care" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-26T07:00:00Z",
    deadline: "2026-10-05T17:00:00Z",
    original_currency: "EUR",
    original_value: 14500000,
    value_usd: 15805000,
    compliance_criteria: ["Pflegeversicherungsgesetz compliance", "German care quality standards", "GDPR"],
    cpv_codes: ["85311000-2"],
    url: "https://ted.europa.eu/notice/2026-SOC-1002",
  },
  {
    external_id: "CANADA-2026-SOC-1003",
    source: "canada_buys" as TenderSource,
    title: "Home Care Services for Seniors — Ontario Health Regions",
    description: "Delivery of in-home personal support, nursing, and rehabilitation services for seniors across 8 Ontario health regions",
    buyer_name: "Ontario Health",
    buyer_country: "CA",
    buyer_region: "North America",
    category: "social_care" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-29T12:00:00Z",
    deadline: "2026-10-08T20:00:00Z",
    original_currency: "CAD",
    original_value: 19700000,
    value_usd: 14617700,
    compliance_criteria: ["Ontario Regulation 246/22", "PIPEDA", "Home care accreditation standards"],
    cpv_codes: ["85312100-0"],
    url: "https://canadabuys.canada.ca/opportunity/2026-SOC-1003",
  },
  // ===== Other — Europe, North America & Asia-Pacific =====
  {
    external_id: "MANUAL-SG-2026-OTH-1101",
    source: "manual" as TenderSource,
    title: "Healthcare Waste Management Services — Singapore Public Healthcare Clusters",
    description: "Collection, transport, and disposal of clinical and hazardous healthcare waste across all public hospitals and polyclinics",
    buyer_name: "Ministry of Health — Singapore (Synapxe)",
    buyer_country: "SG",
    buyer_region: "Asia-Pacific",
    category: "other" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-23T01:00:00Z",
    deadline: "2026-09-11T10:00:00Z",
    original_currency: "SGD",
    original_value: 4100000,
    value_usd: 3034000,
    compliance_criteria: ["NEA licensing", "ISO 14001", "Biohazard handling regulations"],
    cpv_codes: ["90524000-6"],
    url: "https://www.gebiz.gov.sg/2026-OTH-1101",
  },
  {
    external_id: "SAM-DHA-26-OTH-1102",
    source: "sam_gov" as TenderSource,
    title: "Medical Equipment Sterilization Services — Defense Health Agency",
    description: "Centralized sterile processing and equipment sterilization services for 15 military treatment facilities",
    buyer_name: "Defense Health Agency",
    buyer_country: "US",
    buyer_region: "North America",
    category: "other" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-11T14:00:00Z",
    deadline: "2026-09-02T23:59:00Z",
    original_currency: "USD",
    original_value: 8300000,
    value_usd: 8300000,
    compliance_criteria: ["AAMI ST79 standards", "Joint Commission standards", "DoD cybersecurity"],
    cpv_codes: ["90524000-6"],
    url: "https://sam.gov/opp/DHA-26-OTH-1102",
  },
  {
    external_id: "FIND-A-TENDER-2026-OTH-1103",
    source: "find_a_tender" as TenderSource,
    title: "Healthcare Linen and Laundry Services — NHS Wales",
    description: "Provision of hygienic linen supply, laundering, and textile management services for hospitals across NHS Wales health boards",
    buyer_name: "NHS Wales Shared Services Partnership",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "other" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-30T08:00:00Z",
    deadline: "2026-10-01T12:00:00Z",
    original_currency: "GBP",
    original_value: 5900000,
    value_usd: 7493000,
    compliance_criteria: ["HTM 01-04 compliance", "NHS commercial standards", "ISO 9001"],
    cpv_codes: ["98310000-9"],
    url: "https://www.find-tender.service.gov.uk/Notice/2026-OTH-1103",
  },
];

const SAMPLE_AWARDS = [
  {
    tender_id: null as string | null,
    award_date: "2026-05-20T00:00:00Z",
    supplier_name: "Becton Dickinson",
    supplier_country: "US",
    original_currency: "USD",
    award_value: 8700000,
    award_value_usd: 8700000,
    framework_type: "Single supplier",
    duration: "36 months",
    source: "who_procurement" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-05-01T00:00:00Z",
    supplier_name: "Omnicell Inc.",
    supplier_country: "US",
    original_currency: "USD",
    award_value: 38000000,
    award_value_usd: 38000000,
    framework_type: "Single supplier",
    duration: "60 months",
    source: "sam_gov" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-04-10T00:00:00Z",
    supplier_name: "3M Healthcare",
    supplier_country: "US",
    original_currency: "USD",
    award_value: 21000000,
    award_value_usd: 21000000,
    framework_type: "Multi-supplier framework",
    duration: "24 months",
    source: "who_procurement" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-06-12T00:00:00Z",
    supplier_name: "Siemens Healthineers",
    supplier_country: "DE",
    original_currency: "EUR",
    award_value: 18500000,
    award_value_usd: 20165000,
    framework_type: "Single supplier",
    duration: "48 months",
    source: "ted_europa" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-03-28T00:00:00Z",
    supplier_name: "Smith & Nephew",
    supplier_country: "GB",
    original_currency: "GBP",
    award_value: 42000000,
    award_value_usd: 53340000,
    framework_type: "Multi-supplier framework",
    duration: "48 months",
    source: "nhs_supply_chain" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-02-15T00:00:00Z",
    supplier_name: "Roche Diagnostics",
    supplier_country: "CH",
    original_currency: "CHF",
    award_value: 12000000,
    award_value_usd: 13560000,
    framework_type: "Single supplier",
    duration: "36 months",
    source: "ted_europa" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-06-01T00:00:00Z",
    supplier_name: "Medtronic",
    supplier_country: "IE",
    original_currency: "EUR",
    award_value: 15200000,
    award_value_usd: 16568000,
    framework_type: "Single supplier",
    duration: "36 months",
    source: "ted_europa" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-04-22T00:00:00Z",
    supplier_name: "Epic Systems",
    supplier_country: "US",
    original_currency: "USD",
    award_value: 55000000,
    award_value_usd: 55000000,
    framework_type: "Single supplier",
    duration: "84 months",
    source: "sam_gov" as TenderSource,
  },
];

const SAMPLE_BENCHMARKS = [
  {
    region: "Europe",
    category: "medical_devices" as ProcurementCategory,
    avg_lead_time_days: 95,
    avg_contract_value_usd: 18500000,
    tender_count: 342,
    award_count: 198,
    compliance_rate: 87.5,
    period: "2026-Q2",
  },
  {
    region: "North America",
    category: "medical_devices" as ProcurementCategory,
    avg_lead_time_days: 72,
    avg_contract_value_usd: 24300000,
    tender_count: 218,
    award_count: 156,
    compliance_rate: 92.1,
    period: "2026-Q2",
  },
  {
    region: "Europe",
    category: "pharmaceuticals" as ProcurementCategory,
    avg_lead_time_days: 110,
    avg_contract_value_usd: 12700000,
    tender_count: 287,
    award_count: 165,
    compliance_rate: 91.3,
    period: "2026-Q2",
  },
  {
    region: "North America",
    category: "pharmaceuticals" as ProcurementCategory,
    avg_lead_time_days: 85,
    avg_contract_value_usd: 31500000,
    tender_count: 195,
    award_count: 142,
    compliance_rate: 94.7,
    period: "2026-Q2",
  },
  {
    region: "Europe",
    category: "health_it" as ProcurementCategory,
    avg_lead_time_days: 130,
    avg_contract_value_usd: 8900000,
    tender_count: 156,
    award_count: 89,
    compliance_rate: 78.4,
    period: "2026-Q2",
  },
  {
    region: "North America",
    category: "health_it" as ProcurementCategory,
    avg_lead_time_days: 105,
    avg_contract_value_usd: 45600000,
    tender_count: 134,
    award_count: 98,
    compliance_rate: 85.2,
    period: "2026-Q2",
  },
  {
    region: "Africa",
    category: "diagnostics" as ProcurementCategory,
    avg_lead_time_days: 145,
    avg_contract_value_usd: 4200000,
    tender_count: 89,
    award_count: 52,
    compliance_rate: 72.6,
    period: "2026-Q2",
  },
  {
    region: "Asia-Pacific",
    category: "medical_devices" as ProcurementCategory,
    avg_lead_time_days: 88,
    avg_contract_value_usd: 11200000,
    tender_count: 178,
    award_count: 121,
    compliance_rate: 83.9,
    period: "2026-Q2",
  },
  {
    region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    avg_lead_time_days: 78,
    avg_contract_value_usd: 6800000,
    tender_count: 124,
    award_count: 87,
    compliance_rate: 89.1,
    period: "2026-Q2",
  },
  {
    region: "Europe",
    category: "diagnostics" as ProcurementCategory,
    avg_lead_time_days: 92,
    avg_contract_value_usd: 9400000,
    tender_count: 201,
    award_count: 134,
    compliance_rate: 90.8,
    period: "2026-Q2",
  },
  {
    region: "North America",
    category: "laboratory_equipment" as ProcurementCategory,
    avg_lead_time_days: 98,
    avg_contract_value_usd: 15800000,
    tender_count: 87,
    award_count: 61,
    compliance_rate: 88.5,
    period: "2026-Q2",
  },
  {
    region: "Asia-Pacific",
    category: "personal_protective_equipment" as ProcurementCategory,
    avg_lead_time_days: 62,
    avg_contract_value_usd: 3100000,
    tender_count: 145,
    award_count: 112,
    compliance_rate: 76.3,
    period: "2026-Q2",
  },
];

async function seed() {
  const client = getSupabaseClient();
  logger.info("Seeding database with sample data");

  // Clear existing data
  await client.from("contract_awards").delete().neq("id", "00000000-0000-0000-0000-000000000000");
  await client.from("tenders").delete().neq("id", "00000000-0000-0000-0000-000000000000");
  await client.from("supply_chain_benchmarks").delete().neq("id", "00000000-0000-0000-0000-000000000000");

  const { data: tenders, error: tenderErr } = await client
    .from("tenders")
    .upsert(
      SAMPLE_TENDERS.map((t) => ({ ...t, id: uuidv4() })),
      { onConflict: "source,external_id" }
    )
    .select("id, external_id");

  if (tenderErr) {
    logger.error("Failed to seed tenders", { error: tenderErr.message });
    return;
  }

  logger.info("Seeded tenders", { count: tenders?.length });

  // Link awards to their tenders where possible
  const whoTender = tenders?.find((t) => t.external_id === "WHO-PRO-2026-DIAG-078");
  const dodTender = tenders?.find((t) => t.external_id === "SAM-DOD-26-R-0455");
  const ppeTender = tenders?.find((t) => t.external_id === "WHO-PRO-2026-PPE-103");

  if (whoTender) SAMPLE_AWARDS[0].tender_id = whoTender.id;
  if (dodTender) SAMPLE_AWARDS[1].tender_id = dodTender.id;
  if (ppeTender) SAMPLE_AWARDS[2].tender_id = ppeTender.id;

  const { error: awardErr } = await client.from("contract_awards").insert(
    SAMPLE_AWARDS.map((a) => ({ ...a, id: uuidv4() }))
  );
  if (awardErr) {
    logger.error("Failed to seed awards", { error: awardErr.message });
  } else {
    logger.info("Seeded awards", { count: SAMPLE_AWARDS.length });
  }

  // Seed benchmarks
  const { error: benchErr } = await client.from("supply_chain_benchmarks").upsert(
    SAMPLE_BENCHMARKS.map((b) => ({ ...b, id: uuidv4() })),
    { onConflict: "region,category,period" }
  );
  if (benchErr) {
    logger.error("Failed to seed benchmarks", { error: benchErr.message });
  } else {
    logger.info("Seeded benchmarks", { count: SAMPLE_BENCHMARKS.length });
  }

  logger.info("Seed complete");
}

seed().catch((err) => {
  logger.error("Seed failed", { error: String(err) });
  process.exit(1);
});
