import { v4 as uuidv4 } from "uuid";
import { getSupabaseClient } from "./client.js";
import { logger } from "../utils/logger.js";
import type { ProcurementCategory, TenderSource, TenderStatus } from "../types/index.js";

const SAMPLE_TENDERS = [
  {
    external_id: "TED-2026-001234",
    source: "ted_europa" as TenderSource,
    title: "Supply of MRI Scanners for Regional Hospital Network — Germany",
    description: "Framework agreement for supply, installation, and maintenance of 3T MRI systems across 12 university hospitals in Bavaria",
    buyer_name: "Bayerische Krankenhausgesellschaft",
    buyer_country: "DE",
    buyer_region: "Europe",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-05-15T08:00:00Z",
    deadline: "2026-08-30T17:00:00Z",
    original_currency: "EUR",
    original_value: 28500000,
    value_usd: 31065000,
    compliance_criteria: ["CE marking", "ISO 13485", "EU MDR 2017/745"],
    cpv_codes: ["33111000-1"],
    url: "https://ted.europa.eu/notice/2026-001234",
  },
  {
    external_id: "SAM-W912DY-26-R-0089",
    source: "sam_gov" as TenderSource,
    title: "Telehealth Platform for Veterans Affairs Medical Centers",
    description: "Acquisition of cloud-based telehealth and remote patient monitoring platform for 37 VA medical centers nationwide",
    buyer_name: "Department of Veterans Affairs",
    buyer_country: "US",
    buyer_region: "North America",
    category: "telemedicine" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-01T14:00:00Z",
    deadline: "2026-09-15T23:59:00Z",
    original_currency: "USD",
    original_value: 42000000,
    value_usd: 42000000,
    compliance_criteria: ["FedRAMP High", "HIPAA", "Section 508", "FISMA"],
    cpv_codes: ["85140000-2"],
    url: "https://sam.gov/opp/W912DY-26-R-0089",
  },
  {
    external_id: "NHS-SC-2026-PPE-0456",
    source: "nhs_supply_chain" as TenderSource,
    title: "National PPE Framework — Surgical Gowns and Drapes",
    description: "Multi-lot framework for supply of sterile and non-sterile surgical gowns, drapes, and procedural packs to NHS Trusts across England",
    buyer_name: "NHS Supply Chain",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "personal_protective_equipment" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-05-20T09:00:00Z",
    deadline: "2026-08-15T12:00:00Z",
    original_currency: "GBP",
    original_value: 15000000,
    value_usd: 19050000,
    compliance_criteria: ["BSI certification", "NHS commercial standards", "Modern Slavery Act"],
    cpv_codes: ["33199000-1"],
    url: "https://nhssupplychain.nhs.uk/frameworks/PPE-0456",
  },
  {
    external_id: "WHO-PRO-2026-DIAG-078",
    source: "who_procurement" as TenderSource,
    title: "Rapid Diagnostic Test Kits — Sub-Saharan Africa Distribution",
    description: "Procurement of WHO-prequalified rapid diagnostic test kits for malaria, HIV, and tuberculosis for distribution across 14 countries",
    buyer_name: "World Health Organization",
    buyer_country: "CH",
    buyer_region: "Africa",
    category: "diagnostics" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-03-01T10:00:00Z",
    deadline: "2026-05-15T23:59:00Z",
    original_currency: "USD",
    original_value: 8700000,
    value_usd: 8700000,
    compliance_criteria: ["WHO prequalification", "GMP certification", "ISO 13485"],
    cpv_codes: ["33124100-6"],
    url: "https://www.who.int/procurement/DIAG-078",
  },
  {
    external_id: "TED-2026-005678",
    source: "ted_europa" as TenderSource,
    title: "Laboratory Automation Systems — Swedish National Board of Health",
    description: "Design, supply, and commissioning of fully automated clinical laboratory systems for 6 regional laboratories in Sweden",
    buyer_name: "Socialstyrelsen",
    buyer_country: "SE",
    buyer_region: "Europe",
    category: "laboratory_equipment" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-10T07:00:00Z",
    deadline: "2026-09-20T16:00:00Z",
    original_currency: "SEK",
    original_value: 180000000,
    value_usd: 17280000,
    compliance_criteria: ["CE-IVD", "ISO 15189", "GDPR data handling"],
    cpv_codes: ["38000000-5"],
    url: "https://ted.europa.eu/notice/2026-005678",
  },
  {
    external_id: "SAM-HHS-26-R-0312",
    source: "sam_gov" as TenderSource,
    title: "Electronic Health Records Modernisation — Indian Health Service",
    description: "Implementation of next-generation EHR system across 46 Indian Health Service hospitals and 340 outpatient clinics",
    buyer_name: "Indian Health Service",
    buyer_country: "US",
    buyer_region: "North America",
    category: "health_it" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-15T14:00:00Z",
    deadline: "2026-10-01T23:59:00Z",
    original_currency: "USD",
    original_value: 67000000,
    value_usd: 67000000,
    compliance_criteria: ["HIPAA", "Section 508", "HL7 FHIR R4", "FedRAMP Moderate"],
    cpv_codes: ["48000000-8"],
    url: "https://sam.gov/opp/HHS-26-R-0312",
  },
  {
    external_id: "TED-2026-008901",
    source: "ted_europa" as TenderSource,
    title: "Cardiac Catheterisation Laboratory Equipment — Paris Hospitals",
    description: "Supply and installation of 8 cardiac catheterisation laboratory systems for Assistance Publique – Hôpitaux de Paris",
    buyer_name: "AP-HP (Assistance Publique – Hôpitaux de Paris)",
    buyer_country: "FR",
    buyer_region: "Europe",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-04-20T09:00:00Z",
    deadline: "2026-07-31T17:00:00Z",
    original_currency: "EUR",
    original_value: 22000000,
    value_usd: 23980000,
    compliance_criteria: ["CE marking", "ISO 13485", "EU MDR 2017/745", "ANSM registration"],
    cpv_codes: ["33100000-1"],
    url: "https://ted.europa.eu/notice/2026-008901",
  },
  {
    external_id: "NHS-SC-2026-SURG-0789",
    source: "nhs_supply_chain" as TenderSource,
    title: "Orthopaedic Implants and Instruments Framework",
    description: "National framework for hip, knee, shoulder, and trauma implant systems including surgical instruments and associated services",
    buyer_name: "NHS Supply Chain",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-01T08:00:00Z",
    deadline: "2026-09-01T12:00:00Z",
    original_currency: "GBP",
    original_value: 85000000,
    value_usd: 107950000,
    compliance_criteria: ["BSI certification", "MHRA registration", "NHS commercial standards"],
    cpv_codes: ["33183000-6"],
    url: "https://nhssupplychain.nhs.uk/frameworks/SURG-0789",
  },
  {
    external_id: "WHO-PRO-2026-VAX-092",
    source: "who_procurement" as TenderSource,
    title: "Cold Chain Equipment for Vaccine Distribution — Southeast Asia",
    description: "Solar-powered vaccine refrigerators and cold chain monitoring systems for immunisation programmes across 6 ASEAN countries",
    buyer_name: "World Health Organization",
    buyer_country: "CH",
    buyer_region: "Asia-Pacific",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-05-01T10:00:00Z",
    deadline: "2026-08-01T23:59:00Z",
    original_currency: "USD",
    original_value: 14500000,
    value_usd: 14500000,
    compliance_criteria: ["WHO PQS prequalification", "IEC 60068", "GMP certification"],
    cpv_codes: ["33100000-1"],
    url: "https://www.who.int/procurement/VAX-092",
  },
  {
    external_id: "SAM-DOD-26-R-0455",
    source: "sam_gov" as TenderSource,
    title: "Automated Pharmacy Dispensing Systems — Military Health System",
    description: "Supply and installation of automated medication dispensing cabinets for 55 military treatment facilities worldwide",
    buyer_name: "Defense Health Agency",
    buyer_country: "US",
    buyer_region: "North America",
    category: "pharmaceuticals" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-02-01T14:00:00Z",
    deadline: "2026-04-30T23:59:00Z",
    original_currency: "USD",
    original_value: 38000000,
    value_usd: 38000000,
    compliance_criteria: ["FDA 21 CFR Part 11", "HIPAA", "DoD cybersecurity"],
    cpv_codes: ["33600000-6"],
    url: "https://sam.gov/opp/DOD-26-R-0455",
  },
  {
    external_id: "TED-2026-011234",
    source: "ted_europa" as TenderSource,
    title: "Point-of-Care Ultrasound Devices — Netherlands Hospital Group",
    description: "Framework agreement for portable and handheld ultrasound systems across 8 hospitals in the Erasmus MC network",
    buyer_name: "Erasmus MC",
    buyer_country: "NL",
    buyer_region: "Europe",
    category: "medical_devices" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-20T07:00:00Z",
    deadline: "2026-09-30T17:00:00Z",
    original_currency: "EUR",
    original_value: 5200000,
    value_usd: 5668000,
    compliance_criteria: ["CE marking", "ISO 13485", "EU MDR 2017/745"],
    cpv_codes: ["33112000-8"],
    url: "https://ted.europa.eu/notice/2026-011234",
  },
  {
    external_id: "NHS-SC-2026-DIAG-1023",
    source: "nhs_supply_chain" as TenderSource,
    title: "Next-Generation Sequencing Platforms — NHS Genomic Medicine",
    description: "Supply of NGS sequencing instruments and reagent kits for the NHS Genomic Medicine Service across 7 Genomic Laboratory Hubs",
    buyer_name: "NHS England",
    buyer_country: "GB",
    buyer_region: "Europe",
    category: "diagnostics" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-05T08:00:00Z",
    deadline: "2026-08-20T12:00:00Z",
    original_currency: "GBP",
    original_value: 32000000,
    value_usd: 40640000,
    compliance_criteria: ["UKAS accreditation", "CE-IVD", "ISO 15189"],
    cpv_codes: ["33120000-7"],
    url: "https://nhssupplychain.nhs.uk/frameworks/DIAG-1023",
  },
  {
    external_id: "SAM-CDC-26-R-0678",
    source: "sam_gov" as TenderSource,
    title: "Biosafety Level 3 Laboratory Upgrades — CDC Facilities",
    description: "Design and construction of BSL-3 containment upgrades at 4 CDC laboratory facilities including HVAC and decontamination systems",
    buyer_name: "Centers for Disease Control and Prevention",
    buyer_country: "US",
    buyer_region: "North America",
    category: "hospital_infrastructure" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-05-10T14:00:00Z",
    deadline: "2026-08-10T23:59:00Z",
    original_currency: "USD",
    original_value: 29000000,
    value_usd: 29000000,
    compliance_criteria: ["BMBL 6th edition", "OSHA 29 CFR 1910", "EPA regulations"],
    cpv_codes: ["45000000-7"],
    url: "https://sam.gov/opp/CDC-26-R-0678",
  },
  {
    external_id: "WHO-PRO-2026-PPE-103",
    source: "who_procurement" as TenderSource,
    title: "Surgical Masks and N95 Respirators — Global Emergency Stockpile",
    description: "Replenishment of WHO emergency stockpile with surgical masks, N95 respirators, and face shields for pandemic preparedness",
    buyer_name: "World Health Organization",
    buyer_country: "CH",
    buyer_region: "Africa",
    category: "personal_protective_equipment" as ProcurementCategory,
    status: "awarded" as TenderStatus,
    published_at: "2026-01-15T10:00:00Z",
    deadline: "2026-03-30T23:59:00Z",
    original_currency: "USD",
    original_value: 21000000,
    value_usd: 21000000,
    compliance_criteria: ["WHO prequalification", "NIOSH N95 approval", "EN 14683"],
    cpv_codes: ["33199000-1"],
    url: "https://www.who.int/procurement/PPE-103",
  },
  {
    external_id: "TED-2026-014567",
    source: "ted_europa" as TenderSource,
    title: "Hospital Information System — Italian National Health Service",
    description: "Cloud-based HIS platform for 15 public hospitals in Lombardy including patient management, scheduling, and clinical documentation",
    buyer_name: "Regione Lombardia — Direzione Generale Welfare",
    buyer_country: "IT",
    buyer_region: "Europe",
    category: "health_it" as ProcurementCategory,
    status: "open" as TenderStatus,
    published_at: "2026-06-18T09:00:00Z",
    deadline: "2026-10-15T17:00:00Z",
    original_currency: "EUR",
    original_value: 45000000,
    value_usd: 49050000,
    compliance_criteria: ["GDPR", "AgID cloud qualification", "HL7 FHIR", "ISO 27001"],
    cpv_codes: ["48000000-8"],
    url: "https://ted.europa.eu/notice/2026-014567",
  },
];

const SAMPLE_AWARDS = [
  {
    tender_id: null as string | null,
    award_date: "2026-05-20T00:00:00Z",
    supplier_name: "Becton Dickinson",
    supplier_country: "US",
    original_currency: "USD",
    award_value: 8700000,
    award_value_usd: 8700000,
    framework_type: "Single supplier",
    duration: "36 months",
    source: "who_procurement" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-05-01T00:00:00Z",
    supplier_name: "Omnicell Inc.",
    supplier_country: "US",
    original_currency: "USD",
    award_value: 38000000,
    award_value_usd: 38000000,
    framework_type: "Single supplier",
    duration: "60 months",
    source: "sam_gov" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-04-10T00:00:00Z",
    supplier_name: "3M Healthcare",
    supplier_country: "US",
    original_currency: "USD",
    award_value: 21000000,
    award_value_usd: 21000000,
    framework_type: "Multi-supplier framework",
    duration: "24 months",
    source: "who_procurement" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-06-12T00:00:00Z",
    supplier_name: "Siemens Healthineers",
    supplier_country: "DE",
    original_currency: "EUR",
    award_value: 18500000,
    award_value_usd: 20165000,
    framework_type: "Single supplier",
    duration: "48 months",
    source: "ted_europa" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-03-28T00:00:00Z",
    supplier_name: "Smith & Nephew",
    supplier_country: "GB",
    original_currency: "GBP",
    award_value: 42000000,
    award_value_usd: 53340000,
    framework_type: "Multi-supplier framework",
    duration: "48 months",
    source: "nhs_supply_chain" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-02-15T00:00:00Z",
    supplier_name: "Roche Diagnostics",
    supplier_country: "CH",
    original_currency: "CHF",
    award_value: 12000000,
    award_value_usd: 13560000,
    framework_type: "Single supplier",
    duration: "36 months",
    source: "ted_europa" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-06-01T00:00:00Z",
    supplier_name: "Medtronic",
    supplier_country: "IE",
    original_currency: "EUR",
    award_value: 15200000,
    award_value_usd: 16568000,
    framework_type: "Single supplier",
    duration: "36 months",
    source: "ted_europa" as TenderSource,
  },
  {
    tender_id: null as string | null,
    award_date: "2026-04-22T00:00:00Z",
    supplier_name: "Epic Systems",
    supplier_country: "US",
    original_currency: "USD",
    award_value: 55000000,
    award_value_usd: 55000000,
    framework_type: "Single supplier",
    duration: "84 months",
    source: "sam_gov" as TenderSource,
  },
];

const SAMPLE_BENCHMARKS = [
  {
    region: "Europe",
    category: "medical_devices" as ProcurementCategory,
    avg_lead_time_days: 95,
    avg_contract_value_usd: 18500000,
    tender_count: 342,
    award_count: 198,
    compliance_rate: 87.5,
    period: "2026-Q2",
  },
  {
    region: "North America",
    category: "medical_devices" as ProcurementCategory,
    avg_lead_time_days: 72,
    avg_contract_value_usd: 24300000,
    tender_count: 218,
    award_count: 156,
    compliance_rate: 92.1,
    period: "2026-Q2",
  },
  {
    region: "Europe",
    category: "pharmaceuticals" as ProcurementCategory,
    avg_lead_time_days: 110,
    avg_contract_value_usd: 12700000,
    tender_count: 287,
    award_count: 165,
    compliance_rate: 91.3,
    period: "2026-Q2",
  },
  {
    region: "North America",
    category: "pharmaceuticals" as ProcurementCategory,
    avg_lead_time_days: 85,
    avg_contract_value_usd: 31500000,
    tender_count: 195,
    award_count: 142,
    compliance_rate: 94.7,
    period: "2026-Q2",
  },
  {
    region: "Europe",
    category: "health_it" as ProcurementCategory,
    avg_lead_time_days: 130,
    avg_contract_value_usd: 8900000,
    tender_count: 156,
    award_count: 89,
    compliance_rate: 78.4,
    period: "2026-Q2",
  },
  {
    region: "North America",
    category: "health_it" as ProcurementCategory,
    avg_lead_time_days: 105,
    avg_contract_value_usd: 45600000,
    tender_count: 134,
    award_count: 98,
    compliance_rate: 85.2,
    period: "2026-Q2",
  },
  {
    region: "Africa",
    category: "diagnostics" as ProcurementCategory,
    avg_lead_time_days: 145,
    avg_contract_value_usd: 4200000,
    tender_count: 89,
    award_count: 52,
    compliance_rate: 72.6,
    period: "2026-Q2",
  },
  {
    region: "Asia-Pacific",
    category: "medical_devices" as ProcurementCategory,
    avg_lead_time_days: 88,
    avg_contract_value_usd: 11200000,
    tender_count: 178,
    award_count: 121,
    compliance_rate: 83.9,
    period: "2026-Q2",
  },
  {
    region: "Europe",
    category: "surgical_instruments" as ProcurementCategory,
    avg_lead_time_days: 78,
    avg_contract_value_usd: 6800000,
    tender_count: 124,
    award_count: 87,
    compliance_rate: 89.1,
    period: "2026-Q2",
  },
  {
    region: "Europe",
    category: "diagnostics" as ProcurementCategory,
    avg_lead_time_days: 92,
    avg_contract_value_usd: 9400000,
    tender_count: 201,
    award_count: 134,
    compliance_rate: 90.8,
    period: "2026-Q2",
  },
  {
    region: "North America",
    category: "laboratory_equipment" as ProcurementCategory,
    avg_lead_time_days: 98,
    avg_contract_value_usd: 15800000,
    tender_count: 87,
    award_count: 61,
    compliance_rate: 88.5,
    period: "2026-Q2",
  },
  {
    region: "Asia-Pacific",
    category: "personal_protective_equipment" as ProcurementCategory,
    avg_lead_time_days: 62,
    avg_contract_value_usd: 3100000,
    tender_count: 145,
    award_count: 112,
    compliance_rate: 76.3,
    period: "2026-Q2",
  },
];

async function seed() {
  const client = getSupabaseClient();
  logger.info("Seeding database with sample data");

  // Clear existing data
  await client.from("contract_awards").delete().neq("id", "00000000-0000-0000-0000-000000000000");
  await client.from("tenders").delete().neq("id", "00000000-0000-0000-0000-000000000000");
  await client.from("supply_chain_benchmarks").delete().neq("id", "00000000-0000-0000-0000-000000000000");

  const { data: tenders, error: tenderErr } = await client
    .from("tenders")
    .upsert(
      SAMPLE_TENDERS.map((t) => ({ ...t, id: uuidv4() })),
      { onConflict: "source,external_id" }
    )
    .select("id, external_id");

  if (tenderErr) {
    logger.error("Failed to seed tenders", { error: tenderErr.message });
    return;
  }

  logger.info("Seeded tenders", { count: tenders?.length });

  // Link awards to their tenders where possible
  const whoTender = tenders?.find((t) => t.external_id === "WHO-PRO-2026-DIAG-078");
  const dodTender = tenders?.find((t) => t.external_id === "SAM-DOD-26-R-0455");
  const ppeTender = tenders?.find((t) => t.external_id === "WHO-PRO-2026-PPE-103");

  if (whoTender) SAMPLE_AWARDS[0].tender_id = whoTender.id;
  if (dodTender) SAMPLE_AWARDS[1].tender_id = dodTender.id;
  if (ppeTender) SAMPLE_AWARDS[2].tender_id = ppeTender.id;

  const { error: awardErr } = await client.from("contract_awards").insert(
    SAMPLE_AWARDS.map((a) => ({ ...a, id: uuidv4() }))
  );
  if (awardErr) {
    logger.error("Failed to seed awards", { error: awardErr.message });
  } else {
    logger.info("Seeded awards", { count: SAMPLE_AWARDS.length });
  }

  // Seed benchmarks
  const { error: benchErr } = await client.from("supply_chain_benchmarks").upsert(
    SAMPLE_BENCHMARKS.map((b) => ({ ...b, id: uuidv4() })),
    { onConflict: "region,category,period" }
  );
  if (benchErr) {
    logger.error("Failed to seed benchmarks", { error: benchErr.message });
  } else {
    logger.info("Seeded benchmarks", { count: SAMPLE_BENCHMARKS.length });
  }

  logger.info("Seed complete");
}

seed().catch((err) => {
  logger.error("Seed failed", { error: String(err) });
  process.exit(1);
});
